// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsrbgvdldyjooswkxxgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcmJndmRsZHlqb29zd2t4eGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODUzMjcsImV4cCI6MjA2NDU2MTMyN30.i1L2zgia9hJNner9cx-A2iwe1Gs8SOwbqZPPgNEAUn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);